### PR TITLE
dependencies: don't need oppo_common anymore

### PR DESCRIPTION
**Pull request by Raienryu97**
With reference to commit : ee86bf77a418e53cd210c1e757b075197976cffa
We have detached from oppo and don't need to sync it anymore

Change-Id: Ifd1724780fbee02a79fb208c450e2edd1adb8198

### CODE REVIEW

**Comment by jgcaaprom** [comment]
Hello. What do you mean? thanks

**Comment by Raienryu97** [comment]
Since we're detaching from oppo common, I figured having it as a dependency also would not be useful. We don't need device/oppo/common to be synced anymore do we. So this.

**Comment by jgcaaprom** [comment]
but I already have that. or do you mean on cm.dependencies?

**Comment by Raienryu97** [comment]
I'm guessing , we don't need device/oppo/common anymore since we anyway de-linked from there. So it's best not to sync it through dependencies . That's what I wanted to convey.

**Comment by jgcaaprom** [comment]
Alright i've understood, but the commit it is appearing for me is the "Say Goodbye To Oppo" you wish to share is the other one of cm dependencies right ? you can send i'll approve :) Thanks for helping.

**Comment by Raienryu97** [comment]
Haha. Yes. I meant cm.dependencies. 
Thanks
=D

**Pull request merged**
